### ISSUE TITLE
Хотелки в будущих версиях

### ISSUE THREAD

**Issue by booroondook-eng** [vooon/hass-myheat#37]
Не хочу показаться нескромным (тем более, что и сам готов принять посильное участие в развитии проекта), но тем не менее очень хотелось бы расширения функционала, а именно:
1) Определение типа зоны (температура помещения, бойлер, уличная температура, бассейн, смесительный узел и т.д. - всего там, кажется, десять вариантов) и в зависимости от типа зоны уставка предельных значений температуры (например, для температуры помещения от 7 до 35 градусов, для бойлера от 30 до 70 градусов и т.д.). Кроме того, если тип зоны не подразумевает установку целевой температуры (например, уличная температура), то передачу в ХА данной зоны не как термостата, а как простого сенсора (датчика температуры).
2) Получение информации зон по параметрам "demand" (запрос тепла) и "severity/severityDesc" (текущее состояние - нет ли ошибки и т.д.)
3) По аналогии с зонами (envs) - трансляция в ХА также и инженерного оборудования (engs) с дифференциацией по типам (кран, клапан, насос и т.д.), получением текущего состояния и возможностью управления из ХА (например, смена режима - открю, закр., авто). Также, как и с зонами - проверку на ошибки по параметрам severity/severityDesc.
4) Трансляция в ХА отопителей (котлов) с получением всей возможной информации - текущие температуры теплоносителя и обратки, давление, доступность, состояние работы, модуляция, подогрев ГВС и т.д. Возможность включения и отключения котла (котлов). Возможность в ХА деактивировать отдельные параметры (например, если котел в силу своих конструктивных особенностей не сообщает какие-то данные или передает для них нулевое значение). Возможность подмены таких данных данными от других датчиков, имеющихся в ХА.
5) Мониторинг и отображение общих данных MyHeat - состояние системы (severity/severityDesc), уличная температура по данным из Интернета (weatherTemp), актуальность данных (dataActual = true/false), географическое местоположение системы (city).

P.S. все вышеупомянутые данные выдаются по запросу "get_device_info", я не придумал никакой "отсебятины". Ниже даю пример такого запроса, как это выглядит у меня:
```
friendly_name: 'Контроллер: информация об устройстве'
heaters:
  - id: 234
    name: Котёл
    disabled: false
    flowTemp: 48
    returnTemp: 35.75
    pressure: null
    targetTemp: null
    burnerWater: false
    burnerHeating: false
    modulation: 0
envs:
  - id: 109
    type: room_temperature
    name: 3-й этаж
    value: 22.875
    target: 21
    demand: false
    severity: 1
    severityDesc: Нормальное состояние.
  - id: 247
    type: floor_temperature
    name: Тёплый пол
    value: 25.25
    target: 24
    demand: false
    severity: 1
    severityDesc: Нормальное состояние.
  - id: 220
    type: room_temperature
    name: 2-й этаж
    value: 22.375
    target: 22
    demand: false
    severity: 1
    severityDesc: Нормальное состояние.
  - id: 235
    type: boiler_temperature
    name: Бойлер
    value: 56.6875
    target: 60
    demand: true
    severity: 1
    severityDesc: Нормальное состояние.
  - id: 219
    type: outdoor_temperature
    name: Уличная температура
    value: 5.9375
    target: 7
    demand: false
    severity: 1
    severityDesc: Нормальное состояние.
  - id: 80
    type: circuit_temperature
    name: Контур отопления
    value: 48.089999999999996
    target: 7
    demand: false
    severity: 1
    severityDesc: Нормальное состояние.
  - id: 107
    type: room_temperature
    name: 1-й этаж
    value: 22.25
    target: 22
    demand: false
    severity: 1
    severityDesc: Нормальное состояние.
engs:
  - id: 136
    type: two_way_valve
    name: Кран 2-го этажа
    turnedOn: false
    mode: -1
    severity: 1
    severityDesc: Дана команда на закрытие.
  - id: 115
    type: two_way_valve
    name: Кран тёплого пола
    turnedOn: false
    mode: -1
    severity: 1
    severityDesc: Дана команда на закрытие.
  - id: 114
    type: two_way_valve
    name: Кран 3-го этажа
    turnedOn: false
    mode: -1
    severity: 1
    severityDesc: Дана команда на закрытие.
  - id: 113
    type: two_way_valve
    name: Кран 1-го этажа
    turnedOn: false
    mode: -1
    severity: 1
    severityDesc: Дана команда на закрытие.
alarms: []
dataActual: true
severity: 1
severityDesc: Система работает нормально.
weatherTemp: '8.830000000000041'
city: Простоквашино
```
