### ISSUE TITLE
Не отображается текущий пресет отопления

### ISSUE THREAD

**Issue by timurvafin** [vooon/hass-myheat#64]
HA Core: 2024.4.0
MyHeat: 0.4.0

Логи:
```
2024-04-04 22:47:09.783 DEBUG (MainThread) [custom_components.myheat] Data: {'data': {'heaters': [{'id': 12, 'name': 'Котел', 'disabled': False, 'flowTemp': 25.889999999999997, 'returnTemp': None, 'pressure': None, 'targetTemp': None, 'burnerWater': False, 'burnerHeating': False, 'modulation': 0, 'severity': 1, 'severityDesc': 'Котел работает исправно.'}], 'envs': [{'id': 94, 'type': 'boiler_temperature', 'name': 'Горячая вода', 'value': 58.8, 'target': 60, 'demand': False, 'severity': 1, 'severityDesc': 'Нормальное состояние.'}, {'id': 95, 'type': 'room_temperature', 'name': 'Температура помещения', 'value': 25, 'target': 24, 'demand': False, 'severity': 1, 'severityDesc': 'Нормальное состояние.'}], 'engs': [], 'alarms': [], 'dataActual': True, 'severity': 32, 'severityDesc': 'Низкий баланс SIM-карты.', 'weatherTemp': '5.980000000000018', 'city': 'Столбищи'}, 'err': 0, 'refreshPage': False}


2024-04-04 22:39:21.386 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.myheat.climate.MhEnvClimate'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/vooon/hass-myheat/issues
```

Карточка:
```
  - type: thermostat
    entity: climate.myheat_temperatura_pomeshcheniia
    features:
      - type: climate-preset-modes
        style: dropdown
        preset_modes:
          - home
          - eco
          - sleep
          - away
          - none
      - type: climate-hvac-modes
        hvac_modes:
          - 'off'
          - heat
    show_current_as_primary: false

```

Проблема:

- Если в интерфейсе карточки выбирать режим, то в myheat.net от успешно переключается, после перезагрузки страницы в HA сбрасывается на None

https://github.com/vooon/hass-myheat/assets/571/381a8675-47ea-4ffb-b21e-e0a092ac2dfd
